###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
  "idrol": 8005,
  "nombrerol": "Mesero",
  "descrol": "Este rol permitirá de recibir los pedidos",
  "permisosrol": "Permiso 1"
}

###
GET http://localhost:9000/api/users HTTP/1.1

###
GET http://localhost:9000/api/users/64f1fec3ab58eb4a154b5fdb HTTP/1.1

###
DELETE http://localhost:9000/api/users/650086908d8b2c1e21a65e2c HTTP/1.1

###
PUT http://localhost:9000/api/users/64f1fe46ab58eb4a154b5fd9 HTTP/1.1
Content-Type: application/json

{
  "name": "John Arley Restrepo",
  "age": 20,
  "email": "Arleyxd@gmail.com"
}